include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    prefer_final_fields: true
    avoid_print: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_lambdas: true
    prefer_relative_imports: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
